source 'https://rubygems.org'

# thread manager for ruby
# https://ruby-concurrency.github.io/concurrent-ruby/master/file.thread_pools.html
gem 'concurrent-ruby', '~> 1.1', '>= 1.1.9'

# postgresql + dependencies
gem 'hoe'
gem 'hoe-bundler'
gem 'hoe-deveiate'
gem 'hoe-highline'
gem 'hoe-mercurial'
gem 'rake-compiler'
gem 'rake-compiler-dock'
gem 'rdoc'
gem 'pg', '~> 1.0'

# redis store
gem 'redis'

# WebSocket handler
# https://github.com/imanel/websocket-eventmachine-server
gem 'websocket-eventmachine-server'

# tests handler
gem 'rspec'

# api server
gem 'sinatra'
gem 'rack'
gem 'thin'
gem 'puma'
gem 'webrick'

# yaml parser
gem 'yaml'

# watch files changes
gem 'listen'

# colorzing texts in terminal
gem 'colorize'

# json parser
gem 'json'

# bcrypt
gem 'bcrypt'