source 'https://rubygems.org'

# thread manager for ruby
# https://ruby-concurrency.github.io/concurrent-ruby/master/file.thread_pools.html
gem 'concurrent-ruby', '~> 1.1', '>= 1.1.9'

# mongodb
# https://docs.mongodb.com/ruby-driver/master/tutorials/quick-start/
gem "mongo", "~> 2"

# WebSocket handler
# https://github.com/imanel/websocket-eventmachine-server
gem 'websocket-eventmachine-server'

# tests handler
gem 'rspec'

# api server
gem 'sinatra'

# yaml parser
gem 'yaml'